Repository TakwimuAfrica/Takwimu.AFRICA, pull requests merged in 2019-11, with the labels that each got.

#32 Add conditions when querying the total_populations table
  package.json
  src/config.js
  yarn.lock
Labels: bug, enhancement

#33 Performance boost using Lighthouse tips
  pages/_document.js
  pages/profiles/[geoIdOrCountrySlug]/index.js
Labels: enhancement

#36 Featured Data
  package.json
  pages/index.js
  pages/profiles/[geoIdOrCountrySlug]/index.js
  src/components/AnalysisContent/index.js
  src/components/DataContainer/FlourishChart.js
  src/components/DataContainer/HURUmapChart.js
  src/components/FeaturedData.js
  src/getTakwimuPage.js
  src/pages/Profile.js
  src/utils/getHydrateContent.js
Labels: enhancement

#37 Sharing is Caring
  src/common.js
  src/components/DataContainer/FlourishChart.js
  src/components/DataContainer/HURUmapChart.js
  src/pages/Profile.js
Labels: bug, enhancement

#38 [Hotfix] Switch to `now` for deployment
  package.json
  yarn.lock
Labels: enhancement

#39 [Hotfix] Production
  .env
  next.config.js
  package.json
  pages/legal.js
  pages/privacy.js
  pages/profiles/[geoIdOrCountrySlug]/[analysisSlug]/index.js
  pages/terms.js
  public/android-chrome-192x192.png
  public/android-chrome-256x256.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/manifest.json
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  src/components/AnalysisPage.js
  src/components/DataContainer/FlourishChart.js
  src/components/DataContainer/HURUmapChart.js
  src/components/ProfilePage.js
  src/config.js
  src/data/sources.json
  src/pages/_app.js
  src/pages/_document.js
  src/pages/_error.js
  src/pages/about.js
  src/pages/contact.js
  src/pages/embed/[geoId]/[sectionId]/[chartId]/index.js
  src/pages/faqs.js
  src/pages/index.js
  src/pages/legal.js
  src/pages/methodology.js
  src/pages/privacy.js
  src/pages/profiles/[geoIdOrCountrySlug]/[analysisSlug]/index.js
  src/pages/profiles/[geoIdOrCountrySlug]/index.js
  src/pages/search.js
  src/pages/services.js
  src/pages/terms.js
  src/theme.js
  static/pace.css
  static/site.webmanifest
  yarn.lock
Labels: bug, dependencies, enhancement

#40 [Hotfix] Route 66
  package.json
  src/components/AboutContent/AboutUsContentNav.js
  src/components/AnalysisContent/Actions/DownloadPDF.js
  src/components/AnalysisContent/Actions/index.js
  src/components/AnalysisContent/ContentNavigation.js
  src/components/AnalysisContent/TableOfContent.js
  src/components/AnalysisContent/index.js
  src/components/AnalysisContent/topics/CarouselTopic.js
  src/components/AnalysisPage.js
  src/components/ContactContent/index.js
  src/components/ContentNavigation.js
  src/components/CountryContent/index.js
  src/components/DataContainer/ImageDataContainer.js
  src/components/DataContainer/PDFDataContainer.js
  src/components/FeaturedAnalysis/CurrentAnalysis.js
  src/components/Footer/QuickLinks.js
  src/components/LegalContent/LegalContentNav.js
  src/components/LegalContent/index.js
  src/components/Link/Button.js
  src/components/Link/NextComposed.js
  src/components/Link/index.js
  src/components/Navigation/DropDownContent.js
  src/components/Next/Analysis.js
  src/components/Next/index.js
  src/components/Portal.js
  src/components/ProfileDetail/index.js
  src/components/ProfilePage.js
  src/components/RelatedContent/Links.js
  src/components/TableOfContent.js
  src/flags.js
  src/modules/pdf.js
  src/pages/profiles/[geoIdOrCountrySlug]/index.js
  yarn.lock
Labels: bug, enhancement

#41 [Hotfix] PDF Download Button ID
  src/components/AnalysisContent/Actions/DownloadPDF.js
Labels: bug

#42 [Hotfix] Flourish Frame Styling
  src/components/DataContainer/FlourishChart.js
  src/config.js
Labels: bug, enhancement

#43 [Hotfix] Don't use theme fonts in Flourish iframe
  src/components/DataContainer/FlourishChart.js
Labels: bug

#44 [Hotfix] Upgrade HURUmap-UI
  src/components/DataContainer/FlourishChart.js
  yarn.lock
Labels: bug, dependencies, enhancement
