Repository TakwimuAfrica/Takwimu.AFRICA, pull requests merged in 2019-09, with the labels that each got.

#9 Fix Other Info Navigation
  src/components/AnalysisContent/ContentNavigation.js
  src/components/AnalysisContent/OtherInfoNav.js
  src/components/ContentNavigation.js
Labels: bug

#10 Embed page + Population detail on profile detail component
  README.md
  package.json
  scripts/chartsDefinitionsApplyUniqueId.js
  src/App.js
  src/components/ChartFactory.js
  src/components/ProfileDetail/index.js
  src/config.js
  src/data/chart.json
  src/data/queries.js
  src/data/useChartDefinitions.js
  src/data/useProfileLoader.js
  src/pages/Embed.js
  src/pages/Profile.js
  src/setupProxy.js
  yarn.lock
Labels: dependencies, documentation, enhancement

#13 [Bugs] Small Fixes and Updates
  src/components/ChartFactory.js
  src/components/ProfileDetail/index.js
  src/data/chart.json
  src/data/queries.js
  src/data/sources.json
  src/pages/Profile.js
  yarn.lock
Labels: bug, enhancement

#14 Enable InsightContainer share action
  src/common.js
  src/components/DataContainer/FlourishDataContainer.js
  src/components/DataContainer/HURUmapDataContainer.js
  src/components/DataContainer/common.js
  src/pages/Profile.js
Labels: enhancement

#15 Add profile section titles
  src/components/ProfileSection/Title.js
  src/components/ProfileSection/index.js
  src/pages/Profile.js
Labels: enhancement

#17 Fix commitChartDefinitions
  package.json
  scripts/chartsDefinitionsApplyUniqueId.js
  src/data/charts.json
  src/data/useChartDefinitions.js
Labels: bug
