Repository TakwimuAfrica/Takwimu.AFRICA, pull requests merged in 2020-03, with the labels that each got.

#101 Integrate with CRM
  src/pages/_document.js
Labels: enhancement, feature

#102 [Hotfix] SEO Structured Data
  src/components/SEO.js
Labels: bug

#103 Bump hurumap-ui
  package.json
  yarn.lock
Labels: enhancement

#100 Use @hurumap-ui/core and reduce bundle size for faster performance
  .babelrc
  babel.config.js
  next.config.js
  package.json
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage.js
  src/components/AnalysisPage/getInitialProps.js
  src/components/AnalysisPage/index.js
  src/components/ContactContent.js
  src/components/ContentNavigation.js
  src/components/DataContainer/DataActions.js
  src/components/DataContainer/PDFDataContainer.js
  src/components/Footer/Initiative.js
  src/components/Footer/StayInTouch.js
  src/components/Footer/Support.js
  src/components/Footer/index.js
  src/components/LatestNewsStories/StoryCard.js
  src/components/LatestNewsStories/index.js
  src/components/Link/index.js
  src/components/Navigation/DropDownContent.js
  src/components/Navigation/LanguageSelector.js
  src/components/Next/index.js
  src/components/PageContentNavigation.js
  src/components/ProfilePage/getInitialProps.js
  src/components/ProfilePage/index.js
  src/components/ProfileSection/Title.js
  src/components/RelatedContent/Links.js
  src/components/SearchResults/DataSearchResultItem.js
  src/components/SearchResults/SearchResultItem.js
  src/components/WhatYouCanDoWithTakwimu.js
  src/config.js
  src/data/sources.json
  src/modules/react-pdf.js
  src/pages/_app.js
  src/pages/_error.js
  src/pages/embed.js
  src/pages/index.js
  src/pages/legal.js
  src/pages/profiles/[geoIdOrCountrySlug]/[analysisSlug]/index.js
  src/pages/profiles/[geoIdOrCountrySlug]/index.js
  src/theme.js
  yarn.lock
Labels: dependencies, enhancement

#105 Bump HURUmap UI
  package.json
  yarn.lock
Labels: bug

#106 Scroll indicator to into view
  src/components/AnalysisPage/getInitialProps.js
  src/components/AnalysisPage/index.js
Labels: bug

#104 Fix Search Page & Results
  src/components/Navigation/SearchDrawer.js
  src/components/SearchInput/Input.js
  src/components/SearchInput/index.js
  src/components/SearchResults/DataSearchResultItem.js
  src/components/SearchResults/SearchResultItem.js
  src/components/SearchResults/SearchResultsContainer.js
  src/components/SearchResults/index.js
  src/pages/search.js
  src/utils/sliceMultiLangData.js
Labels: bug

#111 Countrify based on language
  src/components/FeaturedAnalysis/index.js
  src/components/utils.js
Labels: enhancement

#110 Add language query to URLs
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage/index.js
  src/pages/index.js
Labels: bug

#112 [Hotfix] default value en
  src/components/Navigation/LanguageSelector.js
Labels: bug

#114 Catch all routes + Dynamic Profiles
  .gitignore
  next.config.js
  package.json
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage/getInitialProps.js
  src/components/AnalysisPage/index.js
  src/components/Navigation/index.js
  src/components/ProfilePage/index.js
  src/components/SearchInput/Input.js
  src/pages/404.js
  src/pages/_error.js
  src/pages/embed/[...path].js
  src/pages/profiles/[...geoIdOrCountrySlug].js
  yarn.lock
Labels: dependencies, enhancement, feature

#115 [Hotfix] Add parentSlug for dynamic profiles
  src/components/AnalysisPage/index.js
  src/pages/profiles/[geoIdOrCountrySlug]/[analysisSlug]/index.js
Labels: bug

#116 Custom Hero image for COVID-19 Profile
  src/assets/images/covid-19-hero.png
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage/index.js
Labels: enhancement, feature

#117 COVID-19 Banner
  src/assets/images/covid-19-logo.png
  src/components/Hero.js
Labels: enhancement, feature
