Repository TakwimuAfrica/Takwimu.AFRICA, pull requests merged in 2020-04, with the labels that each got.

#118 Use `:` as separator
  src/components/utils.js
  src/config.js
Labels: enhancement

#119 Table styles
  src/theme.js
Labels: bug, enhancement

#121 [Investigative] Add Permissive CSP to Test iframe font Loading Issue
  src/pages/_app.js
Labels: bug, feature

#122 [Investigative] Remove CSP
  src/pages/_app.js
Labels: bug, feature
