Repository TakwimuAfrica/Takwimu.AFRICA, pull requests merged in 2020-02, with the labels that each got.

#86 [Hotfix] Country Content Component
  src/components/CountryContent/index.js
Labels: bug

#87 Dokku + UI fixes
  Procfile
  app.json
  package.json
  src/components/AnalysisContent/index.js
  src/components/CountryContent/index.js
  src/components/LatestNewsStories/StoryCard.js
  src/pages/profiles/[geoIdOrCountrySlug]/index.js
  src/theme.js
  yarn.lock
Labels: bug

#88 Add DataTables
  package.json
  src/components/ProfilePage.js
  yarn.lock
Labels: feature

#89 [HotFix] Update line theme + bumb hurumap-ui
  package.json
  src/theme.js
Labels: enhancement

#90 Fix analytics by adding a the ga script
  src/pages/_app.js
Labels: bug

#91 [HotFix] Chart and Insight Container Fix
  src/components/ProfilePage.js
  src/theme.js
Labels: bug

#94 Use old google tracking
  src/pages/_app.js
Labels: bug

#95 Update Ethiopian demographic with world bank data
  src/config.js
Labels: enhancement

#97 Hierarchical Language Support
  src/components/AnalysisPage.js
  src/config.js
Labels: enhancement

#96 Language selector
  package.json
  src/assets/images/languages/en.svg
  src/assets/images/languages/fr.svg
  src/cms.js
  src/components/AnalysisPage.js
  src/components/CountryContent/index.js
  src/components/FeaturedAnalysis/CurrentAnalysis.js
  src/components/Link/Button.js
  src/components/Link/index.js
  src/components/Navigation/LanguageSelector.js
  src/components/Navigation/index.js
  src/components/Next/Analysis.js
  src/components/Next/index.js
  src/components/ProfileDetail.js
  src/components/ProfilePage.js
  src/config.js
  src/languages.js
  src/pages/_document.js
  src/pages/about.js
  src/pages/contact.js
  src/pages/index.js
  src/pages/legal.js
  src/theme.js
  yarn.lock
Labels: enhancement
