Repository TakwimuAfrica/Takwimu.AFRICA, pull requests merged in 2020-01, with the labels that each got.

#50 Update Analysis getInitialProps function
  src/components/AnalysisPage.js
Labels: bug, enhancement

#51 Robot Wars
  src/config.js
  src/pages/robots.txt.js
Labels: enhancement

#52 [Hotfix] yarn upgrade
  yarn.lock
Labels: dependencies

#53 Deprecate ACF geography in the frontend
  src/components/AnalysisPage.js
Labels: bug

#54 [Hotfix] SEO
  public/images/logo-white-all.png
  src/components/AnalysisPage.js
  src/components/SEO.js
  src/pages/index.js
Labels: bug

#56 [Hotfix] Analysis page components UI Fixes
  src/components/AnalysisPage.js
  src/components/Footer/StayInTouch.js
  src/components/Footer/Support.js
  src/components/TableOfContent.js
  src/theme.js
Labels: bug

#59 [Hotfix] Profile Detail Header
  src/components/ProfileDetail/index.js
Labels: bug

#60 [Hotfix] semibold Muli font
  src/pages/_document.js
Labels: bug, enhancement

#61 [Hotfix] Where to Next
  src/components/Next/Card.js
Labels: bug

#62 [Hotfix] Latest News & Stories
  src/components/AnalysisPage.js
  src/components/LatestNewsStories/Story.js
  src/components/LatestNewsStories/StoryBlocks.js
  src/components/LatestNewsStories/StoryCard.js
  src/components/LatestNewsStories/StoryList.js
  src/components/LatestNewsStories/index.js
  src/pages/[page]/[post]/index.js
  src/pages/_app.js
  src/pages/_document.js
  src/theme.js
Labels: bug

#65 [Hotfix] Hero
  src/components/Hero.js
Labels: bug

#64 Analysis / Data by Topic component selector
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage.js
  src/components/CountryContent/Selection.js
  src/components/CountryContent/index.js
Labels: bug

#57 Feature embed
  next.config.js
  package.json
  src/cms.js
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage.js
  src/components/ProfilePage.js
  src/pages/[page]/[post]/index.js
  src/pages/[page]/index.js
  src/pages/_app.js
  src/pages/_error.js
  src/pages/about.js
  src/pages/contact.js
  src/pages/embed.js
  src/pages/embed/[geoId]/[chartId]/index.js
  src/pages/index.js
  src/pages/legal.js
  yarn.lock
Labels: enhancement

#69 [Hotfix] Insight Chart Container in Data by Topic pages
  src/components/ProfilePage.js
Labels: bug

#68 [HotFix] Filter hurumap charts for data by topics
  src/cms.js
Labels: bug

#48 Basic Search Functionality & Auto-complete
  package.json
  src/assets/images/right-arrow-white.svg
  src/components/AnalysisPage.js
  src/components/Navigation/SearchDrawer.js
  src/components/SearchInput/Input.js
  src/components/SearchResults/DataSearchResultItem.js
  src/components/SearchResults/SearchResultItem.js
  src/components/SearchResults/SearchResultsContainer.js
  src/components/SearchResults/index.js
  src/config.js
  src/pages/embed.js
  src/pages/search.js
  yarn.lock
Labels: enhancement

#67 Featured Analyis: Adjust lineHeight + 2px solid border for button
  src/components/FeaturedAnalysis/CurrentAnalysis.js
Labels: bug

#70 [Hofix] Embed button
  src/components/ProfilePage.js
Labels: bug

#73 [HotFix] Kenya population to use Census 2019
  src/config.js
Labels: bug

#74 [Hotfix] Year of Takwimu
  src/components/AnalysisContent/Actions/DownloadPDF.js
  src/components/Footer/index.js
  src/components/MakingOfTakwimu.js
Labels: bug

#75 [Hotfix] dependent Axis labels
  src/components/ProfilePage.js
Labels: bug

#76 [Hotfix] Year 2018-2018
  src/components/AnalysisContent/Actions/DownloadPDF.js
  src/components/Footer/index.js
Labels: bug

#77 Fix Search Results Font Styling
  src/components/SearchInput/Input.js
  src/components/SearchInput/index.js
  src/components/SearchResults/SearchResultsContainer.js
Labels: bug

#79 Fix background css
  src/components/Navigation/DropDownButton.js
  src/components/Navigation/DropDownDrawer.js
Labels: bug

#78 Fix contact content
  src/components/ContactContent/TableOfContent.js
  src/components/ContactContent/index.js
  src/components/ContentPage.js
  src/components/RichTextSection.js
  src/components/TableOfContent.js
Labels: bug

#80 [Hotfix] Search Input
  src/assets/images/search-black.svg
  src/components/SearchInput/Input.js
Labels: bug

#81 [Hotfix] URL Structure
  src/components/SearchResults/DataSearchResultItem.js
Labels: bug

#72 NextJS to S3
  .env.tmpl
  .gitignore
  now.json
  package.json
  src/common.js
  src/components/ProfilePage.js
  src/components/SEO.js
  src/config.js
  src/pages/api/share.js
  yarn.lock
Labels: dependencies, enhancement

#82 Fix "Static" Pages
  src/components/AboutContent.js
  src/components/AboutContent/TableOfContent.js
  src/components/AnalysisContent/Actions/DownloadPDF.js
  src/components/AnalysisContent/CarouselTopic.js
  src/components/AnalysisContent/TableOfContent.js
  src/components/AnalysisContent/index.js
  src/components/AnalysisPage.js
  src/components/AsideTableOfContent.js
  src/components/ContactContent.js
  src/components/ContactContent/ContactContentNav.js
  src/components/ContactContent/TableOfContent.js
  src/components/CountrySelector.js
  src/components/Faqs/Faq.js
  src/components/Faqs/index.js
  src/components/FeaturedAnalysis/AnalysisListItem.js
  src/components/FeaturedAnalysis/CurrentAnalysis.js
  src/components/FeaturedAnalysis/index.js
  src/components/Hero.js
  src/components/LatestNewsStories/index.js
  src/components/LegalContent.js
  src/components/LegalContent/ContentNavigation.js
  src/components/LegalContent/LegalContentNav.js
  src/components/LegalContent/TableOfContent.js
  src/components/MakingOfTakwimu.js
  src/components/Navigation/DropDownButton.js
  src/components/Navigation/DropDownContent.js
  src/components/ProfileDetail.js
  src/components/ProfileSection/index.js
  src/components/RichTextSection.js
  src/components/RichTypography.js
  src/components/Section.js
  src/components/Services.js
  src/components/TableOfContent.js
  src/components/WhatYouCanDoWithTakwimu.js
  src/components/core/index.js
  src/components/utils.js
  src/pages/about.js
  src/pages/contact.js
  src/pages/legal.js
Labels: enhancement

#84 [Hotfix] Data by ... Tweaks
  src/components/ProfilePage.js
  src/theme.js
  yarn.lock
Labels: bug, dependencies

#85 [Hotfix] Analysis Page Spacing and Chart Grid
  src/components/CountryContent/index.js
  src/components/Next/Analysis.js
  src/theme.js
Labels: bug
